main: net.herobrine.gamecore.GameCoreMain
name: GameCore
version: 1.1
loadbefore: [BlockHunt]   
commands:
  join:
    description: f
  arena:
    description: Arena management system for admins.
  staffchat:
    description: Send a message to all staff members.
    aliases: [sc]
  skin:
    description: Set your skin! (BETA)